from django.urls import path

from .views import (
    ActivateAddOnView,
    AnalyticsDashboardView,
    CashFlowForecastView,
    CompleteHandoffView,
    ConfirmAddOnView,
    ConfirmMaintenanceDoneView,
    ConfirmTenantPaymentView,
    ConfirmUpgradeView,
    CreateAgreementView,
    CreateBankAccountView,
    CreateBuildingView,
    CreateDepositView,
    CreateTenancyView,
    CreateTicketView,
    CreateUnitView,
    DelinquencyAnalyticsView,
    EndTenancyView,
    FirebaseLandlordAuthView,
    GoogleLoginView,
    HRARentReceiptView,
    InitiateOffboardingView,
    InitiateTenantPaymentView,
    LandlordDashboardView,
    LoginView,
    MaintenanceIntelligenceView,
    MaintenanceRecordListCreateView,
    MeView,
    OffboardingDetailView,
    OnboardingStatusView,
    PayDepositView,
    PaymentReportExportView,
    PropertyROIView,
    SettleDepositView,
    SignAgreementView,
    SignupView,
    SubscriptionView,
    TaxComplianceReportView,
    TenantDashboardView,
    TenantRiskScoringView,
    TicketDetailView,
    TicketListView,
    UpgradeSubscriptionView,
    UploadDocumentView,
    VerifyDocumentView,
)


urlpatterns = [
    path("auth/login/", LoginView.as_view(), name="api-login"),
    path("auth/firebase/landlord/", FirebaseLandlordAuthView.as_view(), name="api-firebase-landlord-auth"),
    path("auth/signup/", SignupView.as_view(), name="api-signup"),
    path("auth/google/", GoogleLoginView.as_view(), name="api-google-login"),
    path("auth/me/", MeView.as_view(), name="api-me"),
    path("landlord/dashboard/", LandlordDashboardView.as_view(), name="api-landlord-dashboard"),
    path("landlord/buildings/", CreateBuildingView.as_view(), name="api-create-building"),
    path("landlord/units/", CreateUnitView.as_view(), name="api-create-unit"),
    path("landlord/bank-accounts/", CreateBankAccountView.as_view(), name="api-create-bank-account"),
    path("landlord/tenancies/", CreateTenancyView.as_view(), name="api-create-tenancy"),
    path("landlord/tenancies/<int:tenancy_id>/end/", EndTenancyView.as_view(), name="api-end-tenancy"),
    # Onboarding
    path("onboarding/<int:tenancy_id>/", OnboardingStatusView.as_view(), name="api-onboarding-status"),
    path("onboarding/<int:tenancy_id>/documents/", UploadDocumentView.as_view(), name="api-upload-document"),
    path("onboarding/<int:tenancy_id>/documents/<int:doc_id>/verify/", VerifyDocumentView.as_view(), name="api-verify-document"),
    path("onboarding/deposit/", CreateDepositView.as_view(), name="api-create-deposit"),
    path("onboarding/deposit/pay/", PayDepositView.as_view(), name="api-pay-deposit"),
    path("onboarding/agreement/", CreateAgreementView.as_view(), name="api-create-agreement"),
    path("onboarding/agreement/sign/", SignAgreementView.as_view(), name="api-sign-agreement"),
    # Tickets
    path("tickets/", TicketListView.as_view(), name="api-ticket-list"),
    path("tickets/create/", CreateTicketView.as_view(), name="api-create-ticket"),
    path("tickets/<int:ticket_id>/", TicketDetailView.as_view(), name="api-ticket-detail"),
    # Offboarding
    path("offboarding/initiate/", InitiateOffboardingView.as_view(), name="api-initiate-offboarding"),
    path("offboarding/<int:tenancy_id>/", OffboardingDetailView.as_view(), name="api-offboarding-detail"),
    path("offboarding/settle-deposit/", SettleDepositView.as_view(), name="api-settle-deposit"),
    path("offboarding/handoff/", CompleteHandoffView.as_view(), name="api-complete-handoff"),
    path("offboarding/maintenance-done/", ConfirmMaintenanceDoneView.as_view(), name="api-maintenance-done"),
    # Subscription & billing
    path("landlord/subscription/", SubscriptionView.as_view(), name="api-subscription"),
    path("landlord/subscription/upgrade/", UpgradeSubscriptionView.as_view(), name="api-subscription-upgrade"),
    path("landlord/subscription/confirm/", ConfirmUpgradeView.as_view(), name="api-subscription-confirm"),
    path("landlord/addons/activate/", ActivateAddOnView.as_view(), name="api-addon-activate"),
    path("landlord/addons/confirm/", ConfirmAddOnView.as_view(), name="api-addon-confirm"),
    # Premium features
    path("landlord/analytics/", AnalyticsDashboardView.as_view(), name="api-analytics"),
    path("landlord/reports/export/", PaymentReportExportView.as_view(), name="api-reports-export"),
    # Premium analytics endpoints
    path("landlord/analytics/delinquency/", DelinquencyAnalyticsView.as_view(), name="api-analytics-delinquency"),
    path("landlord/analytics/cash-flow/", CashFlowForecastView.as_view(), name="api-analytics-cashflow"),
    path("landlord/analytics/roi/", PropertyROIView.as_view(), name="api-analytics-roi"),
    path("landlord/analytics/tenant-risk/", TenantRiskScoringView.as_view(), name="api-analytics-tenant-risk"),
    path("landlord/analytics/maintenance/", MaintenanceIntelligenceView.as_view(), name="api-analytics-maintenance"),
    path("landlord/analytics/tax-report/", TaxComplianceReportView.as_view(), name="api-analytics-tax"),
    # Tenant
    path("tenant/dashboard/", TenantDashboardView.as_view(), name="api-tenant-dashboard"),
    path("tenant/payments/initiate/", InitiateTenantPaymentView.as_view(), name="api-tenant-payment-initiate"),
    path("tenant/payments/confirm/", ConfirmTenantPaymentView.as_view(), name="api-tenant-payment-confirm"),
    # Maintenance records
    path("landlord/maintenance/", MaintenanceRecordListCreateView.as_view(), name="api-maintenance-records"),
    # HRA rent receipt
    path("tenant/hra-receipt/", HRARentReceiptView.as_view(), name="api-hra-receipt"),
]
