# Generated by Django 4.2.29 on 2026-03-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tenant_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
