# Generated by Django 4.2.29 on 2026-03-10 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_tenant_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenancy',
            name='tenant_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenancies_as_tenant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenancies', to='core.unit'),
        ),
    ]
