# Generated by Django 4.2.29 on 2026-03-10 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_subscription_addon'),
    ]

    operations = [
        migrations.CreateModel(
            name='RazorpayOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rent_month', models.CharField(max_length=7)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order_id', models.CharField(max_length=120, unique=True)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=120)),
                ('payment_session_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='created', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='razorpay_orders', to='core.bankaccount')),
                ('tenancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='razorpay_orders', to='core.tenancy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='payment',
            name='juspay_order',
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(default='razorpay', max_length=32),
        ),
        migrations.DeleteModel(
            name='JuspayOrder',
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.razorpayorder'),
        ),
    ]
