# Generated by Django 4.2.29 on 2026-03-10 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_razorpayorder_remove_payment_juspay_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='category',
            field=models.CharField(choices=[('rent', 'Rent'), ('maintenance', 'Maintenance'), ('utilities', 'Utilities'), ('tax', 'Tax'), ('other', 'Other')], default='rent', max_length=32),
        ),
        migrations.AddField(
            model_name='payment',
            name='due_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type', models.CharField(choices=[('preventative', 'Preventative'), ('reactive', 'Reactive / Emergency')], default='reactive', max_length=20)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='core.unit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
