# Generated by Django 4.2.29 on 2026-03-15 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_payment_category_payment_due_on_maintenancerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenancy',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenancy',
            name='onboarding_status',
            field=models.CharField(choices=[('pending_documents', 'Pending Documents'), ('pending_deposit', 'Pending Deposit'), ('pending_agreement', 'Pending Agreement'), ('pending_first_rent', 'Pending First Rent'), ('completed', 'Completed')], default='pending_documents', max_length=24),
        ),
        migrations.AddField(
            model_name='unit',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('under_maintenance', 'Under Maintenance')], default='available', max_length=24),
        ),
        migrations.AlterField(
            model_name='payment',
            name='category',
            field=models.CharField(choices=[('rent', 'Rent'), ('deposit', 'Deposit'), ('agreement_fee', 'Agreement Fee'), ('maintenance', 'Maintenance'), ('utilities', 'Utilities'), ('tax', 'Tax'), ('other', 'Other')], default='rent', max_length=32),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('resolution_provider', models.CharField(blank=True, choices=[('urban_clap', 'Urban Clap'), ('owner', "Owner's Choice"), ('tenant', "Tenant's Choice")], max_length=20)),
                ('resolution_notes', models.TextField(blank=True)),
                ('receipt_url', models.URLField(blank=True, max_length=500)),
                ('tenancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.tenancy')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Offboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('deposit_settled', 'Deposit Settled'), ('final_rent_paid', 'Final Rent Paid'), ('handoff_complete', 'Handoff Complete'), ('under_maintenance', 'Under Maintenance'), ('completed', 'Completed')], default='initiated', max_length=24)),
                ('handoff_document_url', models.URLField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('tenancy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offboarding', to='core.tenancy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partially_refunded', 'Partially Refunded'), ('refunded', 'Refunded')], default='pending', max_length=24)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deduction_reasons', models.TextField(blank=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('refunded_on', models.DateField(blank=True, null=True)),
                ('tenancy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deposit', to='core.tenancy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreement_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fee_paid', models.BooleanField(default=False)),
                ('signed_date', models.DateField(blank=True, null=True)),
                ('document_url', models.URLField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_signature', 'Pending Signature'), ('signed', 'Signed')], default='draft', max_length=24)),
                ('tenancy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agreement', to='core.tenancy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TenantDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(choices=[('aadhar', 'Aadhar Card'), ('pan', 'PAN Card'), ('work_proof', 'Work Proof'), ('student_proof', 'Student / College Proof')], max_length=20)),
                ('doc_number', models.CharField(blank=True, max_length=60)),
                ('file_url', models.URLField(blank=True, max_length=500)),
                ('verified', models.BooleanField(default=False)),
                ('tenancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.tenancy')),
            ],
            options={
                'unique_together': {('tenancy', 'doc_type')},
            },
        ),
    ]
